require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'bicycleApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  target 'bicycleAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  
end

target 'bicycleApp-tvOS' do
  # Pods for bicycleApp-tvOS

  target 'bicycleApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
